/*
 * Color_Sensor.c
 *
 * Created: 01-12-2018 14:45:11
 *  Author: PUSHPENDRA SINGH
 
This experiment demonstrates the use of Color Sensor.

Micro-controller: atmega2560
Optimization: -O0  (For more information read section: Selecting proper optimization
options below figure 2.22 in the Software Manual)
*/

#define F_CPU 16000000 //define F_CPU value
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <math.h> //included to support power function

//You can declare here global variable as per your requirement
volatile unsigned long int pulse = 0; //to keep the track of the number of pulses generated by the color sensor
volatile unsigned long int red, blue, green;       // variable to store the pulse count when read_red function is called

void rgb_port_config (void)
{
	DDRC = 0x07; //setting all the LED pin's direction set as output
	PORTC = 0x07; //setting all the LED pins are set to logic 1
	/*****************************************
	Define DDR and PORT values for the port on which RGB LED is connected
	******************************************/
}

void color_sensor_pin_config(void)
{
	DDRD  = DDRD | 0xFE; //set PD0 as input for color sensor output
	PORTD = PORTD | 0x01; //Enable internal pull-up for PORTD 0 pin
	/*****************************************
	Define DDR and PORT values for the port on which Color sensor is connected
	******************************************/
}

void color_sensor_pin_interrupt_init(void) //Interrupt 0 enable
{
	cli(); //Clears the global interrupt
	EICRA = EICRA | 0x02; // INT0 is set to trigger with falling edge
	EIMSK = EIMSK | 0x01; // Enable Interrupt INT0 for color sensor
	sei(); // Enables the global interrupt
}

//ISR for color sensor
ISR(INT0_vect) // Pass the timer number in place of n in INTn_vect
{
	pulse++; //increment on receiving pulse from the color sensor
}

void init_devices(void)
{
	cli(); //Clears the global interrupt
	//Initialize all the ports here
	rgb_port_config();//led pin configuration
	color_sensor_pin_config();//color sensor pin configuration
	color_sensor_pin_interrupt_init();
	sei();   // Enables the global interrupt
}

//Filter Selection
void filter_red(void)    //Used to select red filter
{
	//Filter Select - red filter
	 PORTD = PORTD & 0xFB; //set S2 low
	 PORTD = PORTD & 0xF7; //set S3 low
}

void filter_green(void)	//Used to select green filter
{
	//Filter Select - green filter
	 PORTD = PORTD | 0x04; //set S2 High
	 PORTD = PORTD | 0x08; //set S3 High
}

void filter_blue(void)	//Used to select blue filter
{
	//Filter Select - blue filter
	 PORTD = PORTD & 0xFB; //set S2 low
	 PORTD = PORTD | 0x08; //set S3 High
}

void filter_clear(void)	//select no filter
{
	//Filter Select - no filter
	 PORTD = PORTD | 0x04; //set S2 High
	 PORTD = PORTD & 0xF7; //set S3 Low
}

//Color Sensing Scaling
void color_sensor_scaling()		//This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 100% scaling is preferable, though you can change the values as per your application by referring datasheet
{
	//Output Scaling 100% from datasheet
	PORTD = PORTD | 0x80; //set S0 high
	PORTD = PORTD | 0x02; //set S1 high
}

void red_led_on(void)
{
	PORTC = PORTC & 0xFE;
	_delay_ms(1000);
	PORTC = PORTC | 0x01;
}

void green_led_on(void)
{
	PORTC = PORTC & 0xFD;
	_delay_ms(1000);
	PORTC = PORTC | 0x02;
}

void blue_led_on(void)
{
	PORTC = PORTC & 0xFB;
	_delay_ms(1000);
	PORTC = PORTC | 0x04;
}

void red_read(void) // function to select red filter and display the color by glowing red LED. The pulse will be more if the color is red. The pulse will be very less if its blue or green.
{
	//Red
	filter_red(); //select red filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	red = pulse;  //store the count in variable called red
}

void green_read(void) // function to select green filter and display the color by glowing green LED. The pulse will be more if the color is green. The pulse will be very less if its red or blue.
{
	//Green
	filter_green(); //select green filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	green = pulse;  //store the count in variable called green
}

void blue_read(void) // function to select blue filter and display the color by glowing blue LED. The pulse will be more if the color is blue. The pulse will be very less if its red or green.
{
	//Blue
	filter_blue(); //select blue filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	blue = pulse;  //store the count in variable called blue
	
}

int main(void)
{
    init_devices();
	color_sensor_scaling();
	
	while(1)
    {
      //Write your code here
	  red_read();
	  green_read();
	  blue_read();
	  if((red > green) && (red > blue))
	  {
		  //red color detected
		  red_led_on();
	  }
	  if((green > blue) && (green>red))
	  {
		  //green color detected
		  green_led_on();
	  }
	  if((blue > red)&& (blue > green))
	  {
		  //blue color detected
		  blue_led_on();
	  }
    }
}
