/*
 * colour_detection.c
 *
 * Created: 06-02-2019 13:10:51
 *  Author: PUSHPENDRA SINGH
 */ 


#define F_CPU 16000000 //define F_CPU value
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <math.h> //included to support power function
#include "lcd.c"

unsigned char ADC_Conversion(unsigned char);
unsigned char ADC_Value;
unsigned char sharp, distance, adc_reading;
unsigned int value;
unsigned char flag = 0;
unsigned char Left_white_line = 0;
unsigned char Center_white_line = 0;
unsigned char Right_white_line = 0;
volatile unsigned long int pulse = 0; //to keep the track of the number of pulses generated by the color sensor
volatile unsigned long int red, blue, green;       // variable to store the pulse count when read_red function is called
void port_init();
void timer5_init();
void velocity(unsigned char, unsigned char);
void motors_delay();


//Function to configure LCD port
void lcd_port_config (void)
{
	DDRC = DDRC | 0xF7; //all the LCD pin's direction set as output
	PORTC = PORTC & 0x80; // all the LCD pins are set to logic 0 except PORTC 7
}

//ADC pin configuration
void adc_pin_config (void)
{
	DDRF = 0x00; //set PORTF direction as input
	PORTF = 0x00; //set PORTF pins floating
	DDRK = 0x00; //set PORTK direction as input
	PORTK = 0x00; //set PORTK pins floating
}

//Function to configure ports to enable robot's motion
void motion_pin_config (void)
{
	DDRB = 0x0F;
	PORTB = 0xF0;
	DDRL = 0x18;   //Setting PL3 and PL4 pins as output for PWM generation
	PORTL = 0x18; //PL3 and PL4 pins are for velocity control using PWM.
}

void color_sensor_pin_config(void)
{
	DDRD  = DDRD | 0xFE; //set PD0 as input for color sensor output
	PORTD = PORTD | 0x01; //Enable internal pull-up for PORTD 0 pin
	/*****************************************
	Define DDR and PORT values for the port on which Color sensor is connected
	******************************************/
}

//Function to initialize Buzzer
void buzzer_pin_config (void)
{
	DDRE = DDRE | 0x08;		//Setting PORTC 3 as output
	PORTE = PORTE & 0xF7;		//Setting PORTC 3 logic low to turnoff buzzer
}

void color_sensor_pin_interrupt_init(void) //Interrupt 0 enable
{
	cli(); //Clears the global interrupt
	EICRA = EICRA | 0x02; // INT0 is set to trigger with falling edge
	EIMSK = EIMSK | 0x01; // Enable Interrupt INT0 for color sensor
	sei(); // Enables the global interrupt
}

void rgb_port_config (void)
{
	DDRA = 0x07; //setting all the LED pin's direction set as output
	PORTA = 0x07; //setting all the LED pins are set to logic 1
	/*****************************************
	Define DDR and PORT values for the port on which RGB LED is connected
	******************************************/
}

//Configure PORTG 0 pin for servo motor 1 operation
void servo1_pin_config (void)
{
	DDRG  = DDRG | 0x01;  //making PORTG 0 pin output
	PORTG = PORTG | 0x01; //setting PORTG 0 pin to logic 1
}

//Configure PORTG 1 pin for servo motor 2 operation
void servo2_pin_config (void)
{
	DDRG  = DDRG | 0x02;  //making PORTG 1 pin output
	PORTG = PORTG | 0x02; //setting PORTG 1 pin to logic 1
}

//ISR for color sensor
ISR(INT0_vect) // Pass the timer number in place of n in INTn_vect
{
	pulse++; //increment on receiving pulse from the color sensor
}

//Function to Initialize PORTS
void port_init()
{
	cli(); //Clears the global interrupt
	servo1_pin_config();
	servo2_pin_config();
	rgb_port_config();
	color_sensor_pin_config();
	color_sensor_pin_interrupt_init();
	lcd_port_config();
	adc_pin_config();
	motion_pin_config();
	buzzer_pin_config();
	sei();   // Enables the global interrupt
}

// Timer 5 initialized in PWM mode for velocity control
// Prescale:256
// PWM 8bit fast, TOP=0x00FF
// Timer Frequency:225.000Hz
void timer5_init()
{
	TCCR5B = 0x00;	//Stop
	TCNT5H = 0xFF;	//Counter higher 8-bit value to which OCR5xH value is compared with
	TCNT5L = 0x01;	//Counter lower 8-bit value to which OCR5xH value is compared with
	OCR5AH = 0x00;	//Output compare register high value for Left Motor
	OCR5AL = 0xFF;	//Output compare register low value for Left Motor
	OCR5BH = 0x00;	//Output compare register high value for Right Motor
	OCR5BL = 0xFF;	//Output compare register low value for Right Motor
	OCR5CH = 0x00;	//Output compare register high value for Motor C1
	OCR5CL = 0xFF;	//Output compare register low value for Motor C1
	TCCR5A = 0xA9;	/*{COM5A1=1, COM5A0=0; COM5B1=1, COM5B0=0; COM5C1=1 COM5C0=0}
 					  For Overriding normal port functionality to OCRnA outputs.
				  	  {WGM51=0, WGM50=1} Along With WGM52 in TCCR5B for Selecting FAST PWM 8-bit Mode*/
	
	TCCR5B = 0x0B;	//WGM12=1; CS12=0, CS11=1, CS10=1 (Prescaler=64)
}



//Function to Initialize ADC
void adc_init()
{
	ADCSRA = 0x00;
	ADCSRB = 0x00;		//MUX5 = 0
	ADMUX = 0x20;		//Vref=5V external --- ADLAR=1 --- MUX4:0 = 0000
	ACSR = 0x80;
	ADCSRA = 0x86;		//ADEN=1 --- ADIE=1 --- ADPS2:0 = 1 1 0
}



//This Function accepts the Channel Number and returns the corresponding Analog Value
unsigned char ADC_Conversion(unsigned char Ch)
{
	unsigned char a;
	if(Ch>7)
	{
		ADCSRB = 0x08;
	}
	Ch = Ch & 0x07;
	ADMUX= 0x20| Ch;
	ADCSRA = ADCSRA | 0x40;		//Set start conversion bit
	while((ADCSRA&0x10)==0);	//Wait for ADC conversion to complete
	a=ADCH;
	ADCSRA = ADCSRA|0x10; //clear ADIF (ADC Interrupt Flag) by writing 1 to it
	ADCSRB = 0x00;
	return a;
}



// This Function prints the Analog Value Of Corresponding Channel No. at required Row
// and Coloumn Location.
void print_sensor(char row, char coloumn,unsigned char channel)
{
	ADC_Value = ADC_Conversion(channel);
	lcd_print(row, coloumn, ADC_Value, 3);
}

void buzzer_on (void)
{
	unsigned char port_restore = 0;
	port_restore = PINE;
	port_restore = port_restore | 0x08;
	PORTE = port_restore;
}

void buzzer_off (void)
{
	unsigned char port_restore = 0;
	port_restore = PINE;
	port_restore = port_restore & 0xF7;
	PORTE = port_restore;
}

//Function for velocity control
void velocity (unsigned char left_motor, unsigned char right_motor)
{
	OCR5AL = (unsigned char)left_motor;
	OCR5BL = (unsigned char)right_motor;
}

//Function used for setting motor's direction
void motion_set (unsigned char Direction)
{
	unsigned char PortARestore = 0;

	Direction &= 0x0F; 		// removing upper nibbel for the protection
	PortARestore = PORTB; 		// reading the PORTA original status
	PortARestore &= 0xF0; 		// making lower direction nibbel to 0
	PortARestore |= Direction; // adding lower nibbel for forward command and restoring the PORTA status
	PORTB = PortARestore; 		// executing the command
}

void forward (void)
{
	motion_set (0x06);
}

void stop (void)
{
	motion_set (0x00);
}


// This Function calculates the actual distance in millimeters(mm) from the input
// analog value of Sharp Sensor.
unsigned int Sharp_GP2D12_estimation(unsigned char adc_reading)
{
	float distance;
	unsigned int distanceInt;
	distance = (int)(10.00*(2799.6*(1.00/(pow(adc_reading,1.1546)))));
	distanceInt = (int)distance;
	if(distanceInt>800)
	{
		distanceInt=800;
	}
	return distanceInt;
}

//Filter Selection
void filter_red(void)    //Used to select red filter
{
	//Filter Select - red filter
	PORTD = PORTD & 0xFB; //set S2 low
	PORTD = PORTD & 0xF7; //set S3 low
}

void filter_green(void)	//Used to select green filter
{
	//Filter Select - green filter
	PORTD = PORTD | 0x04; //set S2 High
	PORTD = PORTD | 0x08; //set S3 High
}

void filter_blue(void)	//Used to select blue filter
{
	//Filter Select - blue filter
	PORTD = PORTD & 0xFB; //set S2 low
	PORTD = PORTD | 0x08; //set S3 High
}

void filter_clear(void)	//select no filter
{
	//Filter Select - no filter
	PORTD = PORTD | 0x04; //set S2 High
	PORTD = PORTD & 0xF7; //set S3 Low
}

//Color Sensing Scaling
void color_sensor_scaling()		//This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 100% scaling is preferable, though you can change the values as per your application by referring datasheet
{
	//Output Scaling 100% from datasheet
	PORTD = PORTD | 0x80; //set S0 high
	PORTD = PORTD | 0x02; //set S1 high
}


void red_led_on(void)
{
	PORTA = PORTA & 0xFE;
	_delay_ms(1000);
	PORTA = PORTA | 0x01;
}

void green_led_on(void)
{
	PORTA = PORTA & 0xFD;
	_delay_ms(1000);
	PORTA = PORTA | 0x02;
}

void blue_led_on(void)
{
	PORTA = PORTA & 0xFB;
	_delay_ms(1000);
	PORTA = PORTA | 0x04;
}

void red_read(void) // function to select red filter and display the color by glowing red LED. The pulse will be more if the color is red. The pulse will be very less if its blue or green.
{
	//Red
	filter_red(); //select red filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	red = pulse;  //store the count in variable called red
}

void green_read(void) // function to select green filter and display the color by glowing green LED. The pulse will be more if the color is green. The pulse will be very less if its red or blue.
{
	//Green
	filter_green(); //select green filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	green = pulse;  //store the count in variable called green
}

void blue_read(void) // function to select blue filter and display the color by glowing blue LED. The pulse will be more if the color is blue. The pulse will be very less if its red or green.
{
	//Blue
	filter_blue(); //select blue filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	blue = pulse;  //store the count in variable called blue
	
}

//Function to rotate Servo 1 by a specified angle in the multiples of 1.86 degrees
void servo_1(unsigned char degrees)
{
	float PositionPanServo = 0;
	PositionPanServo = ((float)degrees / 1.86) + 35.0;
	OCR1AH = 0x00;
	OCR1AL = (unsigned char) PositionPanServo;
}


//Function to rotate Servo 2 by a specified angle in the multiples of 1.86 degrees
void servo_2(unsigned char degrees)
{
	float PositionTiltServo = 0;
	PositionTiltServo = ((float)degrees / 1.86) + 35.0;
	OCR1BH = 0x00;
	OCR1BL = (unsigned char) PositionTiltServo;
}

//servo_free functions unlocks the servo motors from the any angle
//and make them free by giving 100% duty cycle at the PWM. This function can be used to
//reduce the power consumption of the motor if it is holding load against the gravity.

void servo_1_free (void) //makes servo 1 free rotating
{
	OCR1AH = 0x03;
	OCR1AL = 0xFF; //Servo 1 off
}

void servo_2_free (void) //makes servo 2 free rotating
{
	OCR1BH = 0x03;
	OCR1BL = 0xFF; //Servo 2 off
}

void init_devices (void)
{
	cli(); //Clears the global interrupts
	port_init();
	adc_init();
	timer5_init();
	sei(); //Enables the global interrupts
}



//Main Function
int main(void)
{
	color_sensor_scaling();
	init_devices();
	lcd_set_4bit();
	lcd_init();
	
	while(1)
	{
		
		
		print_sensor(1,2,3);							//Prints value of White Line Sensor1
		print_sensor(1,6,2);							//Prints Value of White Line Sensor2
		print_sensor(1,10,1);							//Prints Value of White Line Sensor3
		/*sharp = ADC_Conversion(0);						//Stores the Analog value of front sharp connected to ADC channel 11 into variable "sharp"
		value = Sharp_GP2D12_estimation(sharp);				//Stores Distance calculated in a variable "value".
		lcd_print(1,14,value,3); 						//Prints Value Of Distance in MM measured by Sharp Sensor.
		Left_white_line = ADC_Conversion(3);	//Getting data of Left WL Sensor
		Center_white_line = ADC_Conversion(2);	//Getting data of Center WL Sensor
		Right_white_line = ADC_Conversion(1);	//Getting data of Right WL Sensor

		flag=0;

		print_sensor(1,1,3);	//Prints value of White Line Sensor1
		print_sensor(1,5,2);	//Prints Value of White Line Sensor2
		print_sensor(1,9,1);	//Prints Value of White Line Sensor3
		
		

		if(Center_white_line<0x28)
		{
			flag=1;
			forward();
			velocity(150,150);
		}

		if((Left_white_line>0x28) && (flag==0))
		{
			flag=1;
			forward();
			velocity(130,50);
		}

		if((Right_white_line>0x28) && (flag==0))
		{
			flag=1;
			forward();
			velocity(50,130);
		}

		if(Center_white_line>0x28 && Left_white_line>0x28 && Right_white_line>0x28)
		{
			forward();
			velocity(0,0);
		}*/
	}
}
